### ISSUE TITLE
난이도 필터 기능은 없나요

### ISSUE THREAD

**Issue by ChoiInYeol** [qorjiwon/RecBOJ#11]
저는 실버-골드 실력인데 자꾸 플레 문제가 추천되어서 불편해요;

**Comment by qorjiwon** [comment]
사용자님의 피드백을 반영하여 난이도 필터 기능을 추가하였습니다!
앞으로도 더욱 좋은 서비스를 제공할 수 있도록 노력하겠습니다. 감사합니다😊
